tryber/sd-011-project-trivia-react-redux

package-lock.json
package.json
src/actions/actionTypes.js
src/actions/index.js
src/index.js
src/reducers/index.js
src/reducers/loginReducer.js
src/store/index.js

Configura Redux, Redux Thunk e ApplyMiddleware.

[ Grupo 34 ] Instala e configura projeto para desenvolvimento!

---

package-lock.json
package.json
src/App.js
src/actions/index.js
src/index.js
src/pages/Home.jsx
src/reducers/index.js
src/reducers/questions.js
src/store/index.js

[Main Group 37]Requisito 1

---

package-lock.json
package.json
src/App.js
src/index.js
src/pages/login.jsx
src/reducers/index.js
src/store/index.js

Primeiro Commit - Requisito 1 Realizado.

Requisito 1 Realizado

---

package-lock.json
package.json
src/App.js
src/actions/index.js
src/components/Login.js
src/index.js
src/reducers/index.js
src/reducers/user.js
src/store/index.js

[ Grupo 24 ] - Começando - Requisito 1

---

package-lock.json
package.json
src/actions/index.js
src/pages/Home/Home.jsx
src/reducers/HomeReducer.js
src/reducers/index.js
src/services/getToken.js
src/store/index.js

[Grupo 36] - Requisito 2

---

src/App.js
src/pages/configuration.jsx
src/pages/login.jsx

Main group 42 requisito 3

---

package-lock.json
package.json
src/App.js
src/index.js
src/pages/Login.js
src/reducers/index.js
src/reducers/reducer.js
src/store/index.js

[Grupo 2] Requisito 1

---

src/components/Header.js

Observações:
- Não Implementado na página
- Comentários adicionado caso use redux

[Grupo 27] - Header.js - Requisito 4

---

README.md
package-lock.json
package.json
src/App.js
src/components/common/Layout.jsx
src/components/common/index.js
src/index.js
src/pages/Login.jsx
src/pages/index.js
src/redux/actions/index.js
src/redux/reducers/index.js
src/redux/reducers/userReducer.js
src/redux/store/index.js

Group 19 req01

---

.gitignore
package-lock.json
src/actions/index.js
src/components/Login.jsx
src/reducers/loginReducer.js

[Group - 17] - Add adjustments

---

src/App.css
src/actions/index.js
src/components/GameComponent.js
src/components/PlayerComponent.js
src/pages/login.js
src/pages/screenGame.js
src/reducers/index.js
src/reducers/triviaReducer.js
src/service/tokenApi.js

- Escrever Proptypes no componente GameComponent
- Erro na requisição do token (Requisito 2)

Falta concluir

---

src/components/Question.jsx

[GROUP 37] Requisito 8

---

src/App.js
src/pages/Config.jsx
src/pages/Login.jsx

Group 19 req03

---

cypress/integration/project.spec.js
src/components/Question.jsx
src/pages/Home.jsx

[GROUP 37] Requisito 9

---

src/actions/index.js
src/components/Question.jsx
src/components/Score.jsx
src/components/Timer.jsx
src/pages/Game.jsx
src/reducers/game.js
src/reducers/index.js

[GROUP 37] Requisito 10 quase finalizado

---

cypress/integration/project.spec.js
src/components/Questions.js
src/pages/feedback/Feedback.js

Requisito 13 finalizado, podem aprovar?

[Grupo 36] - Requisito 13

---

src/components/Header.jsx
src/components/Questions.js
src/pages/feedback/Feedback.js

Grupo 36 - Correção requisitos 12 e 13

---

src/App.css
src/components/gameScreen.jsx

conclusão requisto 7

---

src/actions/index.js
src/compoments/Timer.js
src/pages/GamePage.js
src/pages/Login.js
src/reducers/index.js
src/reducers/triviaReducer.js

Finalizado e testado localmente.

Main group 25 requisito08 timer

---

src/pages/Login.js

agora vai..

---

src/components/Questions.js
src/pages/GamePage/GamePage.js

[GRUPO 36] requisito 8

---

src/components/feedback/Scoreboard.jsx
src/components/quiz/ButtonNext.jsx
src/components/quiz/ButtonQuestion.jsx
src/components/quiz/Questions.jsx
src/pages/Feedback.jsx

Fiz o template para o requisito 14, ele depende da quantidade de perguntas acertadas, e também da pontuação.
Tomei a liberdade de criar componentes de botões para passar no lint. 
Componente ButtonQuestion e ButtonNext
Dei uma olhada no requisito 15 e vi que era fácil, e vi um erro de nossa lógica para redirecionar para a tela de feedback.
Erro:
- Ao chegar na última pergunta, é necessário clicar duas vezes no botão Próximo para ser redirecionado a página de feedback, isso gera um erro nos testes também...

[Grupo 12] Dia 3 - Requisito 14 e (*15) + componentes de botoes

---

src/components/gameScreen.jsx

Reverts tryber/sd-011-project-trivia-react-redux#406

Revert "main-group-42-req10"

---

src/components/Timer.jsx
src/components/gameScreen.jsx
src/pages/login.jsx

Requisito 9 realizado, sendo aprovado nos testes.

Requisito 9 OK - Lint OK

---

src/actions/index.js
src/components/Header.jsx
src/components/Questions.js
src/pages/feedback/Feedback.js
src/reducers/ScoreReducer.js
src/reducers/index.js

[Grupo 36] - Requisito 11

---

cypress/integration/project.spec.js
package-lock.json
src/App.js
src/pages/Feedback.jsx
src/pages/Ranking.jsx

[Grupo 37] requisito 16 finalizado

---

src/App.js
src/components/Ranking.js
src/pages/Game.js

Adiciona requisito 16

---

src/App.css
src/App.js
src/components/Header.js
src/components/Questions.js
src/components/Timer.js
src/pages/FeedBack.js
src/pages/Game.js
src/pages/Login.js
src/redux/actions/index.js
src/redux/reducers/gameMechanics.js
src/redux/reducers/index.js
src/redux/reducers/player.js
src/redux/reducers/questions.js

Requisitos 8 9 10 e 11 passando 100% nos testes!
branch ok!

Main group 28 marcos req 8 9 10 11

---

src/App.css
src/components/Header.jsx
src/components/Questions.js
src/components/header.css
src/components/questions.css
src/pages/GamePage/GamePage.js
src/pages/Home/Home.jsx
src/pages/Home/home.css

[x]- style home page.
[x]- validação de email.
[x]- cria funçao com condicao para desabitilar botoes das questoes no disable.
handleDisableButtons() {
const { showNextButton } = this.state;
if (showNextButton) {
return true;
}
return false;
}

[GRUPO 36] - style home page

---

cypress/integration/project.spec.js
src/App.css
src/components/Question.js

requisito 7 concluido

---

src/App.js
src/components/NextAndFeedback.jsx
src/components/Questions.jsx
src/pages/Feedback.jsx
src/pages/Game.jsx

[ Grupo 34 ] Requisito 11

---

src/App.js
src/components/Ranking.jsx
src/pages/feedback.jsx
src/reducers/resultReducer.js

conclusão requisito 16

---

src/actions/index.js
src/components/Header.js
src/components/Question.js
src/reducers/user.js

[Grupo 5] Requisito 9

---

src/App.js
src/components/Timer.js
src/pages/Feedback.js
src/pages/Ranking.js

[Grupo 3] Requisitos 12 a 13 e Timer

---

cypress/integration/project.spec.js
src/actions/index.js
src/components/PlayerHeader.jsx
src/components/QuestionCard.jsx
src/pages/Feedback.jsx
src/reducers/gameReducer.js

[Grupo 32] - Requisito 12

---

cypress/integration/project.spec.js
src/components/GameHeader.jsx
src/pages/Feedback.jsx
src/pages/Game.jsx
src/pages/Login.jsx
src/pages/Ranking.jsx
src/redux/actions/index.js
src/redux/reducers/userReducer.js
src/utils/getGravatarUrl.js

aeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

[Requisito 17 e 18] add eaeeeeeeeeeeeeee

---

package-lock.json
package.json
src/components/Header.css
src/pages/Game.js
src/pages/Ranking.css
src/pages/Ranking.js
src/pages/Settings.css

Adicionei também uma biblioteca para decodificar corretamente os textos das questões e das respostas, que estavam vindo com símbolos estranhos no meio.

[Grupo 7] - Estilização da página de Ranking
